name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script:  | 
            cd /home/ubuntu/deployment/
            if [ ! -d "hawtin-blog" ]; then
              git clone --depth=1 https://github.com/HawtinZeng/hawtin-blog
              cd hawtin-blog
            else
              cd hawtin-blog
              git fetch origin
              git reset --hard origin/main
            fi
              npm install -f --loglevel=error
            npm run build
            cp /home/ubuntu/apps/blog/report.html ./report.html
            rm /home/ubuntu/apps/blog/* -rf
            cp ./report.html /home/ubuntu/apps/blog/report.html
            cp ./dist/* /home/ubuntu/apps/blog/ -r
